import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Layout(props) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <Image
                    src="/public/WEBKITE.png"
                    height={60}
                    width={144}
                    alt="LOGO"
                />
                <nav>
                    <Link href={"/"}>
                        <a>Main</a>
                    </Link>
                    <Link href={"/offers"}>
                        <a>Offers</a>
                    </Link>
                    <Link href={"/portfolio"}>
                        <a>Portfolio</a>
                    </Link>
                    <Link href={"/aboutus"}>
                        <a>About us</a>
                    </Link>
                </nav>

                <Image
                    src="/public/WEBKITE.png"
                    height={60}
                    width={144}
                    alt="LANG"
                />

            </header>
            <main>
                {props.children}
            </main>

            <footer>Footer</footer>
        </div>
    )
}
